### ISSUE TITLE
Allow to add labels to read group addresses.

### ISSUE THREAD

**Issue by chr-fritz** [chr-fritz/knx-exporter#13]
Currently it is not possible to configure static labels exported group address values. This leads to the problem that every group address maps exactly to a metric.

For example there are the rooms office, kitchen and bedroom with a temperature sensor. So every temperature sensor will have it's own group address to publish the meassured temperatures. The current version of the kxn-exporter will publish three metrics `knx_temperature_office`, `knx_temperature_kitchen` and `knx_temperature_bedroom`. This is bad as it will limit the features which can be created in dashboards.

Allowing to add static labels in the configuration of exported metrics could solve this problem.
It will export three values for one metric `knx_temperature` each with a label `room` and the values `office`, `kitchen` and `bedroom`.

The configuration could look like this example:

```yaml
Connection:
  Type: "Tunnel"
  Endpoint: "192.168.1.15:3671"
  PhysicalAddress: 2.0.1
MetricsPrefix: knx_
  0/0/1:
    Name: temperature
    DPT: 9.*
    Export: true
    MetricType: "gauge"
    # This section is new and defines the labels:
    labels:
      room: bedroom
```

This configuration will export a single metric `knx_temperature` with the static label `room` which has the value `bedroom`.
