### ISSUE TITLE
DPTs for date, time and datetime are not recognized correctly

### ISSUE THREAD

**Issue by nomisim** [chr-fritz/knx-exporter#57]
**Describe the bug**
The following DPTs seem to not get recognized correctly:
* DPT 11.001 - date
* DPT 10.001 - time of day
* DPT 19.001 - date time

The following output is produced:
```
WARN[0109] can not find appropriate type for DPT_11001
WARN[0109] can not find appropriate type for DPT_10001
WARN[0110] can not find dpt description for "19.001" to unpack Write telegram from x.y.z for a/b/c
```

**To Reproduce**
1. Configure the DPTs accordingly
```yml
2/0/6:
  Comment: |
    Date STATE
  DPT: "11.001"
  Export: true
  MetricType: gauge
  Name: Date_STATE
2/0/7:
  Comment: |
    Time STATE
  DPT: "10.001"
  Export: true
  MetricType: gauge
  Name: Time_STATE
2/0/8:
  Comment: |
    Date/Time STATE
  DPT: "19.001"
  Export: true
  MetricType: gauge
  Name: Date_Time_STATE
```

**Additional context**
I think DPT 19.X is missing in the used knx library.

I think DPT 11.001 and DPT 10.001 are contained in the used knx library.
