### ISSUE TITLE
Beginner's problem

### ISSUE THREAD

**Issue by wszelakid** [chr-fritz/knx-exporter#99]
Hi, 

I'm having problems with the first start-up

My config: /etc/knx-exporter/config.yaml

```
Connection:
  Type: "Tunnel"
  Endpoint: "192.168.7.203:3671"
  PhysicalAddress: 1.1.228
MetricsPrefix: knx_
AddressConfigs:
 0/0/14:
    DPT: "9.001"
    Export: true
    MetricType: "gauge"
    Name: Temperatura1
    ReadStartup: true
    ReadActive: true
    MaxAge: 10m
    ReadType: GroupRead
```

I'm starting it: 

```
root@test:~# knx-exporter run -f /etc/knx-exporter/config.yaml
Config File ".knx-exporter" Not Found in "[/root]"
time=2024-10-21T16:07:21.543+02:00 level=INFO source=/home/runner/work/knx-exporter/knx-exporter/pkg/knx/exporter.go:114 msg="Connecting to endpoint" endpoint=192.168.7.203:3671 connection_type=tunnel useTcp=false
time=2024-10-21T16:07:21.553+02:00 level=INFO source=/home/runner/work/knx-exporter/knx-exporter/pkg/knx/startup-reader.go:60 msg="start reading addresses after startup." delay=200ms
time=2024-10-21T16:07:21.555+02:00 level=INFO source=/home/runner/work/knx-exporter/knx-exporter/pkg/knx/listener.go:58 msg="Waiting for incoming knx telegrams..." connectionType=Tunnel endpoint=192.168.7.203:3671
```

In web browser i have: http://192.168.7.226:8080/metrics :

```
[...] 
# HELP knx_Temperatura1 
# TYPE knx_Temperatura1 gauge
knx_Temperatura1{physicalAddress="1.1.178"} 16.299999237060547
# HELP knx_messages 
# TYPE knx_messages counter
knx_messages{direction="received",processed="false"} 409
knx_messages{direction="received",processed="true"} 3
knx_messages{direction="sent",processed="true"} 1
[...]
```

but in web interface of Prometheus is no data from KNX:

![2024-10-21 16_13_33-Prometheus Time Series Collection and Processing Server — Mozilla Firefox](https://github.com/user-attachments/assets/b822433e-5d68-4c21-9cf1-8a487a5cc7f4)

Unfortunately I have lost all idea what I am doing wrong

BR,

Daniel

**Comment by chr-fritz** [comment]
Hi,

from that what you described, it looks to me that the knx-exporter is working correctly according to your configuration. But it looks to me that you don't configured your prometheus server correctly. It don't scrape the knx-exporter so no metrics can appear within prometheus. Please check your prometheus configuration.

Here this is the link to the prometheus configuration documenation: https://prometheus.io/docs/prometheus/latest/configuration/configuration/

BR,
Christian

**Comment by wszelakid** [comment]
Hi Christian,

Could you show me sample file?  /etc/prometheus/prometheus.yml

BR,

Daniel

**Comment by wszelakid** [comment]
Hi,

This was necessary in: /etc/prometheus/prometheus.yml

```
[...]
  - job_name: KNX
    static_configs:
      - targets: ['localhost:8080']
```
:)

BR,

Daniel
